### ISSUE TITLE
Wrong size?

### ISSUE THREAD

**Issue by alkanen** [NVlabs/ffhq-dataset#1]
I experience the following, am I doing something wrong? As far as I can tell, this is how the readme file says to start the script, except that it's apparently in Windows rather than Linux.

```
$ python3 ../download_ffhq.py --json --images 
Downloading JSON metadata...
-   0.00% done  1/2 files  0.00/0.25 GB   0.00 B/s    ETA: ...     Traceback (most recent call last):
  File "../download_ffhq.py", line 397, in <module>
    run_cmdline(sys.argv)
  File "../download_ffhq.py", line 392, in run_cmdline
    run(**vars(args))
  File "../download_ffhq.py", line 344, in run
    download_files([json_spec, license_specs['json']], **download_kwargs)
  File "../download_ffhq.py", line 194, in download_files
    raise exc_info[1].with_traceback(exc_info[2])
  File "../download_ffhq.py", line 203, in _download_thread
    download_file(session, spec, stats, **download_kwargs)
  File "../download_ffhq.py", line 82, in download_file
    raise IOError('Incorrect file size', file_path)
OSError: [Errno Incorrect file size] ffhq-dataset-v1.json
```

**Comment by alkanen** [comment]
Okay, looks like this is the reason:
`{'file_url': 'https://drive.google.com/uc?id=1SZVzeMgo4dcHZVBauUH2mXU4Z8P-8ddk', 'file_path': 'thumbnails128x128/LICENSE.txt', ' file_size': 1610, 'file_md5': '724f3831aaecd61a84fe98500079abc2'}`

The file_size field has a space in front, that's a problem.
